import { useEffect, useState } from 'react'
import toast from 'react-hot-toast'
import { Link, useParams } from 'react-router-dom'
import { apiRequest } from '../lib/api'

const monthName = (month) => new Date(2024, month - 1, 1).toLocaleString('default', { month: 'long' })

const PrintPayslip = () => {
  const { id } = useParams()
  const [payslip, setPayslip] = useState(null)

  useEffect(() => {
    apiRequest(`/payslips/${id}`).then(setPayslip).catch((err) => toast.error(err.message))
  }, [id])

  if (!payslip) return <div className="card p-6 text-slate-500">Loading payslip...</div>

  return (
    <div className="animate-fade-in max-w-4xl mx-auto">
      <div className="flex items-center justify-between mb-6 print:hidden"><Link className="btn-secondary" to="/payslips">Back</Link><button className="btn-primary" onClick={() => window.print()}>Print</button></div>
      <div className="card p-8 bg-white">
        <div className="flex items-start justify-between border-b border-slate-200 pb-6">
          <div><h1 className="text-3xl font-bold text-slate-900">Employix Payslip</h1><p className="text-slate-500">{monthName(payslip.month)} {payslip.year}</p></div>
          <span className={`badge ${payslip.status === 'paid' ? 'badge-success' : 'badge-warning'}`}>{payslip.status}</span>
        </div>
        <div className="grid gap-6 sm:grid-cols-2 py-6 border-b border-slate-200"><div><p className="text-sm text-slate-500">Employee</p><p className="font-semibold text-slate-900">{payslip.employee?.firstName} {payslip.employee?.lastName}</p><p className="text-sm text-slate-500">{payslip.employee?.employeeId}</p></div><div><p className="text-sm text-slate-500">Generated By</p><p className="font-semibold text-slate-900">{payslip.generatedBy?.firstName} {payslip.generatedBy?.lastName}</p><p className="text-sm text-slate-500">Generated {new Date(payslip.createdAt).toLocaleDateString()}</p></div></div>
        <div className="mt-6 space-y-3"><div className="flex justify-between"><span>Basic Salary</span><strong>${Number(payslip.basicSalary).toLocaleString()}</strong></div><div className="flex justify-between"><span>Allowances</span><strong>${Number(payslip.allowances).toLocaleString()}</strong></div><div className="flex justify-between text-rose-600"><span>Deductions</span><strong>-${Number(payslip.deductions).toLocaleString()}</strong></div><div className="flex justify-between text-rose-600"><span>Tax</span><strong>-${Number(payslip.tax).toLocaleString()}</strong></div><div className="flex justify-between border-t border-slate-200 pt-4 text-xl"><span>Net Pay</span><strong>${Number(payslip.netPay).toLocaleString()}</strong></div></div>
      </div>
    </div>
  )
}

export default PrintPayslip
